<?php
/**
 * Created by PhpStorm.
 * User: Yaniv Aran-Shamir
 * Date: 7/30/14
 * Time: 1:38 PM
 */

$follow_bar_placeholder = 'this is a placeholder the value here is empty now!
[
    {
         "provider": "facebook",
         "actionURL": "https://www.facebook.com/gigya",
         "action": "dialog"
    },
    {
      "provider": "twitter",
         "followUsers": "gigya, gigyaDev",
         "action": "dialog"
    },
    {
      "provider": "googleplus",
         "actionURL": "https://plus.google.com/107788669599113247501/posts",
         "action": "window"
    },
    {
      "provider": "linkedin",
         "actionURL": "http://www.linkedin.com/company/gigya",
         "action": "window"
    },
    {
      "provider": "rss",
         "actionURL": "http://blog.gigya.com/feed/",
         "action": "window"
    },
    {
      "provider": "email",
         "confirmationText":"Thank you for following us",
         "action": "dialog"
    }
   ]
';