<?php
/**
 * @file
 * Module code for Social Share Counter.
 */

/**
 * Implements hook_permission().
 */
function social_share_counter_permission() {
  return array(
    'administer social_share_counter' => array(
      'title' => t('Administer Social Share Counter module'),
      'description' => t('Perform administration tasks for social_share_counter module.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function social_share_counter_menu() {
  $items['admin/config/social_share_counter'] = array(
    'title' => 'Social Share Counter',
    'description' => 'Admin Social Share Counter',
    'position' => 'left',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/social_share_counter/configuration'] = array(
    'title' => 'Configure',
    'description' => 'Configure Social Share Counter Module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('social_share_counter_settings_form'),
    'access arguments' => array('administer social_share_counter'),
    'file' => 'social_share_counter.admin.inc',
  );
  $items['social_share_counter/share'] = array(
    'page callback' => 'social_share_counter_share',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements of hook_init().
 */
function social_share_counter_init() {

}

/**
 * Implements of hook_page_build().
 */
function social_share_counter_page_build(&$page) {
  // Enable by default or if enabled.
  if (variable_get('ssc_status', 1) == 1) {
    drupal_add_css(drupal_get_path('module', 'social_share_counter') . '/css/font-awesome.min.css');
    drupal_add_css(drupal_get_path('module', 'social_share_counter') . '/css/ssc.css');
    include_once 'social_share_counter.admin.inc';
    // Get admin settings.
    $settings = social_share_counter_settings();
    $option = array(
      'type' => 'file',
      'scope' => 'footer',
      'group' => JS_LIBRARY,
      'cache' => FALSE,
    );
    drupal_add_js($settings['sharrre'], $option);
    $data['button_text'] = array(
      'facebook' => variable_get('ssc_facebook_button_text', 'Share on Facebook'),
      'twitter'	=> variable_get('ssc_facebook_twitter_text', 'Share on Twitter'),
    );
    $data['count_text'] = variable_get('ssc_text_below_count', 'Share');
    $template = theme('social_share_counter', array('data' => $data));
    $my_settings = array(
      'share' => url('social_share_counter/share', array('absolute' => TRUE)),
      'template' => $template,
      'ssc_ga_tracking' => variable_get('ssc_ga_tracking', 1),
      'ssc_min_to_show' => variable_get('ssc_min_to_show', 0),
    );
    drupal_add_js(array('SSC' => $my_settings), "setting");
  }
}

/**
 * Implements hook_node_view().
 */
function social_share_counter_node_view($node, $view_mode) {
  // Don't display if the user is currently searching, or in the RSS feed.
  switch ($view_mode) {
    case 'search_result':
    case 'search_index':
    case 'rss':
      return;
  }
  $types = variable_get('ssc_nodetypes', array('page', 'article'));
  $teaser = ($view_mode == 'teaser') ? TRUE : FALSE;

  $enabled_view_modes = variable_get('ssc_' . $node->type . '_options', array());
  if (isset($enabled_view_modes[$view_mode]) && $enabled_view_modes[$view_mode]) {
    $node->content['ssc'] = array(
      'html' => TRUE,
      '#markup' => _ssc_create_button($node),
      '#weight' => intval(variable_get('ssc_display_weight', -10)),
    );
    $option = array(
      'type' => 'file',
      'scope' => 'footer',
      'group' => JS_LIBRARY,
      'cache' => FALSE,
      'weight' => 10
    );
    drupal_add_js(drupal_get_path('module', 'social_share_counter') . '/js/ssc_main.js', $option);
    if ($view_mode == 'full') {
      $node->page_bottom['devel'] = array(
        '#weight' => 25,
        '#markup' => '<div style="clear:both;">gergter</div>',
      );
      drupal_add_js(drupal_get_path('module', 'social_share_counter') . '/js/ssc_floating_navigation.js', $option);
    }
  }
}
/**
 * Internal function to generate code for Social Share Counter buttons.
 *
 * @param object $node
 *   Optional parameter
 *
 * @return string
 *   String containing HTML code for the buttons
 */
function _ssc_create_button($node=NULL) {
  global $_ssc_num, $base_path;

  $_ssc_num++;

  if (is_object($node)) {
    $link_name 	= (module_exists('page_title')) ? page_title_page_get_title() : $node->title;
    $link_url 	= url('node/' . $node->nid, array('absolute' => 1));
  }
  else {
    // Front page.
    $link_name	= (module_exists('page_title')) ? page_title_page_get_title() : variable_get('site_name', 'Drupal');
    $link_url = url('<front>', array('absolute' => 1));
  }
  // ID is later removed by JS (for AJAX).
  $str = '<aside class="ssc-container"><div class="sharebox" data-url="' . $link_url . '" data-text="' . $link_name . '"></div></aside>';
  return (sprintf($str));
}

/**
 * Implements hook_theme().
 */
function social_share_counter_theme($existing, $type, $theme, $path) {
  return array(
    'social_share_counter' => array(
      'template' => 'social-share-counter',
      'variables' => array('data' => NULL),
      'path' => drupal_get_path('module', 'social_share_counter') . '/',
    ),
    'social_share_counter_follow_box' => array(
      'template' => 'social-share-counter-follow-box',
      'variables' => array('data' => NULL),
      'path' => drupal_get_path('module', 'social_share_counter') . '/',
    ),
  );
}
/**
 * Implements hook_block_info().
 */
function social_share_counter_block_info() {
  $blocks['ssc_follow_box'] = array(
    'info' => t('Social Share Counter Follow Box'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implements of hook_block_view().
 */
function social_share_counter_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'ssc_follow_box':
      $block['content'] = _social_share_counter_block_contents();
      break;
  }
  return $block;
}
/**
 * custom html block
 * @return string
 */
function _social_share_counter_block_contents() {
  $data = array();
  $data['profile_links']['facebook'] = variable_get('ssc_social_media_profile_facebook');
  $data['profile_links']['twitter'] = variable_get('ssc_social_media_profile_twitter');
  $data['profile_links']['google_plus'] = variable_get('ssc_social_media_profile_google_plus');
  $data['profile_links']['linkedin'] = variable_get('ssc_social_media_profile_linkedin');
  $data['profile_links']['pinterest'] = variable_get('ssc_social_media_profile_pinterest');
  $data['profile_links']['stumbleupon'] = variable_get('ssc_social_media_profile_stumbleupon');
  $data['profile_links']['rss'] = variable_get('ssc_profile_rss');

  return theme('social_share_counter_follow_box', array('data' => $data));
}
/**
 * Function to get real time counter.
 */
function social_share_counter_share() {
  header('content-type: application/json');
  $json = array('url' => '','count' => 0);
  $json['url'] = $_GET['url'];
  $url = urlencode($_GET['url']);
  $type = urlencode($_GET['type']);

  if (filter_var($_GET['url'], FILTER_VALIDATE_URL)) {
    if ($type == 'googlePlus') {
      $content = _social_share_counter_parse("https://plusone.google.com/u/0/_/+1/fastbutton?url=" . $url . "&count=true");

      $dom = new DOMDocument();
      $dom->preserveWhiteSpace = FALSE;
      @$dom->loadHTML($content);
      $domxpath = new DOMXPath($dom);

      $filtered = $domxpath->query("//div[@id='aggregateCount']");
      if (isset($filtered->item(0)->nodeValue)) {
        $json['count'] = str_replace('>', '', $filtered->item(0)->nodeValue);
      }
    }
    elseif ($type == 'stumbleupon') {
      $content = _social_share_counter_parse("http://www.stumbleupon.com/services/1.01/badge.getinfo?url=$url");

      $result = json_decode($content);
      if (isset($result->result->views)) {
        $json['count'] = $result->result->views;
      }
    }
    elseif ($type == 'pinterest') {
      $content = _social_share_counter_parse("http://api.pinterest.com/v1/urls/count.json?callback=&url=$url");

      $result = json_decode(str_replace(array('(', ')'), array('', ''), $content));
      if (is_int($result->count)) {
        $json['count'] = $result->count;
      }
    }
  }
  echo str_replace('\\/', '/', json_encode($json));
}
/**
 * Function to parse real time counter request.
 */
function _social_share_counter_parse($enc_url) {
  $options = array(
    CURLOPT_RETURNTRANSFER => TRUE,
    CURLOPT_HEADER => FALSE,
    CURLOPT_FOLLOWLOCATION => TRUE,
    CURLOPT_ENCODING => "",
    CURLOPT_USERAGENT => 'sharrre',
    CURLOPT_AUTOREFERER => TRUE,
    CURLOPT_CONNECTTIMEOUT => 5,
    CURLOPT_TIMEOUT => 10,
    CURLOPT_MAXREDIRS => 3,
    CURLOPT_SSL_VERIFYHOST => 0,
    CURLOPT_SSL_VERIFYPEER => FALSE,
  );
  $ch = curl_init();

  $options[CURLOPT_URL] = $enc_url;
  curl_setopt_array($ch, $options);

  $content = curl_exec($ch);
  $err = curl_errno($ch);
  $errmsg = curl_error($ch);

  curl_close($ch);

  if ($errmsg != '' || $err != '') {
    /*print_r($errmsg);
    print_r($errmsg);*/
  }
  return $content;
}
